/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUS_KhachHang;
import DAO.DAO_KhachHang;
import DTO.DTO_KhachHang;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;

import org.apache.poi.ss.usermodel.Row;

import org.apache.poi.ss.usermodel.Sheet;

import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;

import org.apache.poi.xssf.usermodel.XSSFSheet;

import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author hieu
 */
public class KhachHang extends javax.swing.JFrame {
    ArrayList<DTO_KhachHang> arr = new ArrayList<DTO_KhachHang>();
    BUS_KhachHang khBUS = new BUS_KhachHang();
    int row;

    public KhachHang() {
        initComponents();
        loadKHList();
    }
    
    public void loadKHList(){
        DefaultTableModel dtm = (DefaultTableModel) tb_khachhang.getModel();
        dtm.setRowCount(0);
        arr = khBUS.getAllKhachHangs();
        for (int i = 0; i < arr.size(); i++) {
            String MaNCC = arr.get(i).getMaKhachHang();
            String TenNCC = arr.get(i).getTenKH();
            String SDT = arr.get(i).getSDT();
            String Diachi = arr.get(i).getDiachi();
             String Email = arr.get(i).getEmail();
            Object[] row = {MaNCC,TenNCC,SDT,Diachi,Email};
            dtm.addRow(row);
        }
    }
    public void deleteKHtable(){
        DefaultTableModel dtm = (DefaultTableModel) tb_khachhang.getModel();
        dtm.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll_ncc = new javax.swing.JScrollPane();
        tb_khachhang = new javax.swing.JTable();
        panel_1 = new javax.swing.JPanel();
        lb_welcome = new javax.swing.JLabel();
        panel_themsuaxoa = new javax.swing.JPanel();
        lb_mancc = new javax.swing.JLabel();
        lb_tenncc = new javax.swing.JLabel();
        lb_masdt = new javax.swing.JLabel();
        txt_mancc = new javax.swing.JTextField();
        txt_tenncc = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        lb_diachi = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        panel_timkiem = new javax.swing.JPanel();
        txt_Timkiem = new javax.swing.JTextField();
        btn_exittimkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_excel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scroll_ncc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        scroll_ncc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scroll_nccMouseClicked(evt);
            }
        });

        tb_khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tb_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "SĐT", "Địa Chỉ", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_khachhangMouseClicked(evt);
            }
        });
        scroll_ncc.setViewportView(tb_khachhang);

        lb_welcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lb_welcome.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_1Layout.createSequentialGroup()
                    .addGap(0, 197, Short.MAX_VALUE)
                    .addComponent(lb_welcome)
                    .addGap(0, 197, Short.MAX_VALUE)))
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lb_welcome)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        lb_mancc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_mancc.setText("Mã Khách Hàng");

        lb_tenncc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_tenncc.setText("Tên Khách Hàng");

        lb_masdt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_masdt.setText("SĐT");

        txt_mancc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txt_mancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manccActionPerformed(evt);
            }
        });

        txt_tenncc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txt_sdt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btn_them.setText("THÊM");
        btn_them.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_them.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_them.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("SỬA");
        btn_sua.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_sua.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_sua.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("XÓA");
        btn_xoa.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_xoa.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_xoa.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        RESET.setText("RESET");
        RESET.setMaximumSize(new java.awt.Dimension(100, 30));
        RESET.setMinimumSize(new java.awt.Dimension(100, 30));
        RESET.setPreferredSize(new java.awt.Dimension(100, 30));
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        lb_diachi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_diachi.setText("Địa Chỉ");

        txt_diachi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_email.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_email.setText("E-Mail");

        txt_email.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        javax.swing.GroupLayout panel_themsuaxoaLayout = new javax.swing.GroupLayout(panel_themsuaxoa);
        panel_themsuaxoa.setLayout(panel_themsuaxoaLayout);
        panel_themsuaxoaLayout.setHorizontalGroup(
            panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                        .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_email))
                    .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                        .addComponent(btn_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(RESET, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                        .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_diachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lb_tenncc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(lb_mancc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_masdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mancc)
                            .addComponent(txt_tenncc)
                            .addComponent(txt_sdt)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(26, 26, 26))
        );
        panel_themsuaxoaLayout.setVerticalGroup(
            panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mancc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_mancc))
                .addGap(20, 20, 20)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tenncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_tenncc))
                .addGap(20, 20, 20)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_masdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_sdt))
                .addGap(18, 18, 18)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_diachi)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RESET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        txt_Timkiem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_Timkiem.setForeground(new java.awt.Color(102, 102, 102));
        txt_Timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TimkiemMouseClicked(evt);
            }
        });
        txt_Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimkiemActionPerformed(evt);
            }
        });
        txt_Timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimkiemKeyReleased(evt);
            }
        });

        btn_exittimkiem.setText("EXIT");
        btn_exittimkiem.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_exittimkiem.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_exittimkiem.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_exittimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exittimkiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Tìm Kiếm");

        btn_excel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_excel.setText("Xuất File Excel");
        btn_excel.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_excel.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_excel.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_timkiemLayout = new javax.swing.GroupLayout(panel_timkiem);
        panel_timkiem.setLayout(panel_timkiemLayout);
        panel_timkiemLayout.setHorizontalGroup(
            panel_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timkiemLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_excel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_timkiemLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_exittimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_timkiemLayout.setVerticalGroup(
            panel_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timkiemLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panel_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exittimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_excel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scroll_ncc, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
                    .addComponent(panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(panel_themsuaxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_themsuaxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panel_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scroll_ncc)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        try{
            if (txt_mancc.getText().trim().equals("")||
                txt_tenncc.getText().trim().equals("")||
                txt_sdt.getText().trim().equals("")||
                txt_diachi.getText().trim().equals("")||
                txt_email.getText().trim().equals(""))
                JOptionPane.showConfirmDialog(this, "Vui long nhap du thong tin");
            else {
                DTO_KhachHang mh = new DTO_KhachHang();
                mh.setMaKhachHang((txt_mancc.getText()));
                mh.setTenKH(txt_tenncc.getText());
                mh.setSDT((txt_sdt.getText()));
                mh.setDiachi(txt_diachi.getText());
                mh.setEmail(txt_email.getText());
                JOptionPane.showMessageDialog(this, khBUS.addNCC(mh));
                loadKHList();
            }
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Thong tin khong hop le");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void scroll_nccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scroll_nccMouseClicked
        // TODO add your handling code her
    }//GEN-LAST:event_scroll_nccMouseClicked

    private void tb_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_khachhangMouseClicked
        // TODO add your handling code here:
        row = tb_khachhang.getSelectedRow();
        if (row == -1) return;
        DTO_KhachHang mh = arr.get(row);
        txt_mancc.setText(String.valueOf(mh.getMaKhachHang()));
        txt_tenncc.setText(mh.getTenKH());
        txt_sdt.setText(String.valueOf(mh.getSDT()));
        txt_diachi.setText(String.valueOf(mh.getDiachi()));
        txt_email.setText(mh.getEmail());
    }//GEN-LAST:event_tb_khachhangMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        try{
            if (txt_mancc.getText().trim().equals("")||
                txt_tenncc.getText().trim().equals("")||
                txt_sdt.getText().trim().equals("")||
                txt_diachi.getText().trim().equals("")||
                txt_email.getText().trim().equals(""))
                JOptionPane.showConfirmDialog(this, "Vui long nhap du thong tin");
            else {
                DTO_KhachHang mh = new DTO_KhachHang();
                mh.setMaKhachHang(txt_mancc.getText());
                mh.setTenKH(txt_tenncc.getText());
                mh.setSDT(txt_sdt.getText());
                mh.setDiachi(txt_diachi.getText());
                mh.setEmail(txt_email.getText());
                JOptionPane.showMessageDialog(this, khBUS.chinhsuaKH(mh));
                loadKHList();
            }
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Thong tin khong hop le");
        }       
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        int index = tb_khachhang.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 Khách Hàng trong bảng để xóa", "Thông Báo", 1);
            return;
        }
        DTO_KhachHang mh = new DTO_KhachHang();
        mh.setMaKhachHang(txt_mancc.getText());
                mh.setTenKH(txt_tenncc.getText());
                mh.setSDT(txt_sdt.getText());
                mh.setDiachi(txt_diachi.getText());
                                mh.setEmail(txt_email.getText());
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
      if (tk==JOptionPane.YES_OPTION)  
      {
          
          mh.setTrangThai(0);
          JOptionPane.showMessageDialog(this, khBUS.xoaKH(mh));
          loadKHList();
      }
      else
      {
          return;
          
      }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_manccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manccActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
        txt_mancc.setText("");
        txt_tenncc.setText("");
        txt_sdt.setText("");
        txt_diachi.setText("");
        txt_email.setText("");
        
    }//GEN-LAST:event_RESETActionPerformed

    private void btn_exittimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exittimkiemActionPerformed
        // TODO add your handling code here:
        loadKHList();
    }//GEN-LAST:event_btn_exittimkiemActionPerformed

    private void txt_TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimkiemActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_TimkiemActionPerformed

    private void txt_TimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TimkiemMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_TimkiemMouseClicked

    private void txt_TimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimkiemKeyReleased
        // TODO add your handling code here:
       DefaultTableModel dtm = (DefaultTableModel) tb_khachhang.getModel();
        dtm.setRowCount(0);
        arr = khBUS.timkiem(txt_Timkiem.getText());
        for (int i = 0; i < arr.size(); i++) {
            String MaNCC = arr.get(i).getMaKhachHang();
            String TenNCC = arr.get(i).getTenKH();
            String SDT = arr.get(i).getSDT();
            String Diachi = arr.get(i).getDiachi();
            String Email = arr.get(i).getEmail();
            Object[] row = {MaNCC,TenNCC,SDT,Diachi,Email};
            dtm.addRow(row);
        }
    }//GEN-LAST:event_txt_TimkiemKeyReleased

    private void btn_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excelActionPerformed
        // TODO add your handling code here:
        arr = khBUS.getAllKhachHangs();
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("danhsach");
        XSSFRow row = null;
        Cell cell = null;
        row=sheet.createRow(3);
        cell=row.createCell(0,CellType.STRING);
        cell.setCellValue("STT");
        cell=row.createCell(1,CellType.STRING);
        cell.setCellValue("MaKH");
        cell=row.createCell(2,CellType.STRING);
        cell.setCellValue("TenKH");
        cell=row.createCell(3,CellType.STRING);
        cell.setCellValue("SĐT");
        cell=row.createCell(4,CellType.STRING);
        cell.setCellValue("DiaChi");
        cell=row.createCell(5,CellType.STRING);
        cell.setCellValue("Email");
        for (int i=0; i<arr.size(); i++){
            row=sheet.createRow(4+i);

            cell=row.createCell(0,CellType.NUMERIC);
            cell.setCellValue(i+1);

            cell=row.createCell(1,CellType.STRING);
            cell.setCellValue(arr.get(i).getMaKhachHang());

            cell=row.createCell(2,CellType.STRING);
            cell.setCellValue(arr.get(i).getTenKH());

            cell=row.createCell(3,CellType.STRING);
            cell.setCellValue(arr.get(i).getSDT());

            cell=row.createCell(4,CellType.STRING);
            cell.setCellValue(arr.get(i).getDiachi());
            
            cell=row.createCell(5,CellType.STRING);
            cell.setCellValue(arr.get(i).getEmail());
        }
        File f = new File("D:\\HK2_22-23\\Java\\Quan_Ly_Kho_Hang\\DAJ\\Quan_Ly_Kho_Hang_Java\\src\\excel\\danhsachKhachHang.xlsx");
        try{
            FileOutputStream fis = new FileOutputStream(f);
            workbook.write(fis);
            fis.close();
        }
        catch (FileNotFoundException ex){
            ex.printStackTrace();
        }
        catch (IOException ex){
            ex.printStackTrace();
        }

        JOptionPane.showMessageDialog(this,"In thành công");
    }//GEN-LAST:event_btn_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RESET;
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_exittimkiem;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_diachi;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_mancc;
    private javax.swing.JLabel lb_masdt;
    private javax.swing.JLabel lb_tenncc;
    private javax.swing.JLabel lb_welcome;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_themsuaxoa;
    private javax.swing.JPanel panel_timkiem;
    private javax.swing.JScrollPane scroll_ncc;
    private javax.swing.JTable tb_khachhang;
    private javax.swing.JTextField txt_Timkiem;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_mancc;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenncc;
    // End of variables declaration//GEN-END:variables
}
