/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Truong Hiep
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_home = new javax.swing.JLabel();
        lb_nhanvien = new javax.swing.JLabel();
        lb_sanpham = new javax.swing.JLabel();
        lb_ncc = new javax.swing.JLabel();
        lb_khachhang = new javax.swing.JLabel();
        lb_ThongKe = new javax.swing.JLabel();
        lb_admin = new javax.swing.JLabel();
        lb_dangxuat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_home.setBackground(new java.awt.Color(0, 51, 102));
        lb_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_home.setForeground(new java.awt.Color(255, 255, 255));
        lb_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_home.setText("Home");
        lb_home.setOpaque(true);
        lb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_homeMouseEntered(evt);
            }
        });

        lb_nhanvien.setBackground(new java.awt.Color(0, 51, 102));
        lb_nhanvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        lb_nhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhanvien.setText("Nhân viên");
        lb_nhanvien.setToolTipText("");
        lb_nhanvien.setAutoscrolls(true);
        lb_nhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_nhanvien.setOpaque(true);

        lb_sanpham.setBackground(new java.awt.Color(0, 51, 102));
        lb_sanpham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_sanpham.setForeground(new java.awt.Color(255, 255, 255));
        lb_sanpham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_sanpham.setText("Sản phẩm");

        lb_ncc.setBackground(new java.awt.Color(0, 51, 102));
        lb_ncc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_ncc.setForeground(new java.awt.Color(255, 255, 255));
        lb_ncc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ncc.setText("Nhà cung cấp");
        lb_ncc.setOpaque(true);

        lb_khachhang.setBackground(new java.awt.Color(0, 51, 102));
        lb_khachhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        lb_khachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_khachhang.setText("Khách hàng");

        lb_ThongKe.setBackground(new java.awt.Color(0, 51, 102));
        lb_ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lb_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ThongKe.setText("Thống kê");
        lb_ThongKe.setOpaque(true);

        lb_admin.setBackground(new java.awt.Color(0, 51, 102));
        lb_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_admin.setForeground(new java.awt.Color(255, 255, 255));
        lb_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_admin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Truong Hiep\\OneDrive\\Documents\\NetBeansProjects\\doanJ\\src\\main\\java\\com\\image\\admin.png")); // NOI18N
        lb_admin.setText("(Admin)");
        lb_admin.setIconTextGap(3);

        lb_dangxuat.setBackground(new java.awt.Color(0, 51, 102));
        lb_dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        lb_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dangxuat.setText("Đăng xuất");
        lb_dangxuat.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_sanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_ncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_khachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_dangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_sanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseEntered
        
    }//GEN-LAST:event_lb_homeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_ThongKe;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_dangxuat;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_khachhang;
    private javax.swing.JLabel lb_ncc;
    private javax.swing.JLabel lb_nhanvien;
    private javax.swing.JLabel lb_sanpham;
    // End of variables declaration//GEN-END:variables
}
