/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUS_mathang;
import DAO.DAO_mathang;
import DTO.DTO_mathang;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hieu
 */
public class Sanpham extends javax.swing.JFrame {
    ArrayList<DTO_mathang> arr = new ArrayList<DTO_mathang>();
    BUS_mathang mathangBUS = new BUS_mathang();
    int row;

    public Sanpham() {
        initComponents();
        loadMathangList();
    }
    
    public void loadMathangList(){
        DefaultTableModel dtm = (DefaultTableModel) tb_sanpham.getModel();
        dtm.setRowCount(0);
        arr = mathangBUS.getAllMathang();
        for (int i = 0; i < arr.size(); i++) {
            int mamh = arr.get(i).getMaMatmang();
            String tenmh = arr.get(i).getTenMathang();
            int mancc = arr.get(i).getMaNhacungcap();
            Object[] row = {mamh,tenmh,mancc};
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll_sanpham = new javax.swing.JScrollPane();
        tb_sanpham = new javax.swing.JTable();
        panel_1 = new javax.swing.JPanel();
        lb_welcome = new javax.swing.JLabel();
        panel_themsuaxoa = new javax.swing.JPanel();
        lb_mamathang = new javax.swing.JLabel();
        lb_tenmathang = new javax.swing.JLabel();
        lb_mancc = new javax.swing.JLabel();
        txt_mamathang = new javax.swing.JTextField();
        txt_tenmathang = new javax.swing.JTextField();
        txt_mancc = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        panel_timkiem = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scroll_sanpham.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        scroll_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scroll_sanphamMouseClicked(evt);
            }
        });

        tb_sanpham.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tb_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã mặt hàng", "Tên mặt hàng", "Nhà cung cấp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_sanpham.setRowHeight(20);
        tb_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sanphamMouseClicked(evt);
            }
        });
        scroll_sanpham.setViewportView(tb_sanpham);

        lb_welcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lb_welcome.setText("SẢN PHẨM");

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
            .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_1Layout.createSequentialGroup()
                    .addGap(0, 197, Short.MAX_VALUE)
                    .addComponent(lb_welcome)
                    .addGap(0, 197, Short.MAX_VALUE)))
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lb_welcome)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        lb_mamathang.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_mamathang.setText("Mã mặt hàng");

        lb_tenmathang.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_tenmathang.setText("Tên mặt hàng");

        lb_mancc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_mancc.setText("Mã nhà cung cấp");

        txt_mamathang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txt_mamathang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mamathangActionPerformed(evt);
            }
        });

        txt_tenmathang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txt_mancc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btn_them.setText("THÊM");
        btn_them.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_them.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_them.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("SỬA");
        btn_sua.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_sua.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_sua.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("XÓA");
        btn_xoa.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_xoa.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_xoa.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        RESET.setText("RESET");
        RESET.setMaximumSize(new java.awt.Dimension(100, 30));
        RESET.setMinimumSize(new java.awt.Dimension(100, 30));
        RESET.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout panel_themsuaxoaLayout = new javax.swing.GroupLayout(panel_themsuaxoa);
        panel_themsuaxoa.setLayout(panel_themsuaxoaLayout);
        panel_themsuaxoaLayout.setHorizontalGroup(
            panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                        .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_tenmathang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_mamathang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_mancc, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mamathang)
                            .addComponent(txt_tenmathang)
                            .addComponent(txt_mancc)))
                    .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                        .addComponent(btn_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(RESET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(62, 62, 62))
        );
        panel_themsuaxoaLayout.setVerticalGroup(
            panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_themsuaxoaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mamathang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_mamathang))
                .addGap(20, 20, 20)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tenmathang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_tenmathang))
                .addGap(20, 20, 20)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mancc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_mancc))
                .addGap(39, 39, 39)
                .addGroup(panel_themsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RESET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout panel_timkiemLayout = new javax.swing.GroupLayout(panel_timkiem);
        panel_timkiem.setLayout(panel_timkiemLayout);
        panel_timkiemLayout.setHorizontalGroup(
            panel_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_timkiemLayout.setVerticalGroup(
            panel_timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scroll_sanpham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_themsuaxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_themsuaxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(panel_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scroll_sanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                        .addGap(16, 16, 16)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        try{
            if (txt_mamathang.getText().trim().equals("")||
                txt_tenmathang.getText().trim().equals("")||
                txt_mancc.getText().trim().equals(""))
                JOptionPane.showConfirmDialog(this, "Vui long nhap du thong tin");
            else {
                DTO_mathang mh = new DTO_mathang();
                mh.setMaMatmang(Integer.parseInt(txt_mamathang.getText()));
                mh.setTenMathang(txt_tenmathang.getText());
                mh.setMaNhacungcap(Integer.parseInt(txt_mancc.getText()));
                JOptionPane.showMessageDialog(this, mathangBUS.addMathang(mh));
                loadMathangList();
            }
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Thong tin khong hop le");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void scroll_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scroll_sanphamMouseClicked
        // TODO add your handling code her
    }//GEN-LAST:event_scroll_sanphamMouseClicked

    private void tb_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sanphamMouseClicked
        // TODO add your handling code here:
        row = tb_sanpham.getSelectedRow();
        if (row == -1) return;
        DTO_mathang mh = arr.get(row);
        txt_mamathang.setText(String.valueOf(mh.getMaMatmang()));
        txt_tenmathang.setText(mh.getTenMathang());
        txt_mancc.setText(String.valueOf(mh.getMaNhacungcap()));
    }//GEN-LAST:event_tb_sanphamMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        try{
            if (txt_mamathang.getText().trim().equals("")||
                txt_tenmathang.getText().trim().equals("")||
                txt_mancc.getText().trim().equals(""))
                JOptionPane.showConfirmDialog(this, "Vui long nhap du thong tin");
            else {
                DTO_mathang mh = new DTO_mathang();
                mh.setMaMatmang(Integer.parseInt(txt_mamathang.getText()));
                mh.setTenMathang(txt_tenmathang.getText());
                mh.setMaNhacungcap(Integer.parseInt(txt_mancc.getText()));
                JOptionPane.showMessageDialog(this, mathangBUS.chinhsuaMathang(mh));
                loadMathangList();
            }
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Thong tin khong hop le");
        }       
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_mamathangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mamathangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mamathangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RESET;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel lb_mamathang;
    private javax.swing.JLabel lb_mancc;
    private javax.swing.JLabel lb_tenmathang;
    private javax.swing.JLabel lb_welcome;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_themsuaxoa;
    private javax.swing.JPanel panel_timkiem;
    private javax.swing.JScrollPane scroll_sanpham;
    private javax.swing.JTable tb_sanpham;
    private javax.swing.JTextField txt_mamathang;
    private javax.swing.JTextField txt_mancc;
    private javax.swing.JTextField txt_tenmathang;
    // End of variables declaration//GEN-END:variables
}
