/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Truong Hiep
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        loadhome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_ = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lb_nhapkho = new javax.swing.JLabel();
        lb_xuatkho = new javax.swing.JLabel();
        lb_sanpham = new javax.swing.JLabel();
        lb_nhacungcap = new javax.swing.JLabel();
        lb_khachhang = new javax.swing.JLabel();
        lb_admin = new javax.swing.JLabel();
        lb_dangxuat = new javax.swing.JLabel();
        pn_main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel_.setBackground(new java.awt.Color(255, 255, 255));
        panel_.setPreferredSize(new java.awt.Dimension(250, 700));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 700));

        lb_nhapkho.setBackground(new java.awt.Color(0, 51, 102));
        lb_nhapkho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_nhapkho.setForeground(new java.awt.Color(255, 255, 255));
        lb_nhapkho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhapkho.setText("NHẬP KHO");
        lb_nhapkho.setOpaque(true);
        lb_nhapkho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nhapkhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_nhapkhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_nhapkhoMouseExited(evt);
            }
        });

        lb_xuatkho.setBackground(new java.awt.Color(0, 51, 102));
        lb_xuatkho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_xuatkho.setForeground(new java.awt.Color(255, 255, 255));
        lb_xuatkho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_xuatkho.setText("XUẤT KHO");
        lb_xuatkho.setOpaque(true);
        lb_xuatkho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_xuatkhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_xuatkhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_xuatkhoMouseExited(evt);
            }
        });

        lb_sanpham.setBackground(new java.awt.Color(0, 51, 102));
        lb_sanpham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_sanpham.setForeground(new java.awt.Color(255, 255, 255));
        lb_sanpham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_sanpham.setText("SẢN PHẨM");
        lb_sanpham.setToolTipText("");
        lb_sanpham.setAutoscrolls(true);
        lb_sanpham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_sanpham.setOpaque(true);
        lb_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_sanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_sanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_sanphamMouseExited(evt);
            }
        });

        lb_nhacungcap.setBackground(new java.awt.Color(0, 51, 102));
        lb_nhacungcap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_nhacungcap.setForeground(new java.awt.Color(255, 255, 255));
        lb_nhacungcap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhacungcap.setText("NHÀ CUNG CẤP");
        lb_nhacungcap.setOpaque(true);
        lb_nhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nhacungcapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_nhacungcapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_nhacungcapMouseExited(evt);
            }
        });

        lb_khachhang.setBackground(new java.awt.Color(0, 51, 102));
        lb_khachhang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        lb_khachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_khachhang.setText("KHÁCH HÀNG");
        lb_khachhang.setOpaque(true);
        lb_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_khachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_khachhangMouseExited(evt);
            }
        });

        lb_admin.setBackground(new java.awt.Color(0, 51, 102));
        lb_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_admin.setForeground(new java.awt.Color(255, 255, 255));
        lb_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_admin.setText("(Admin)");
        lb_admin.setIconTextGap(3);

        lb_dangxuat.setBackground(new java.awt.Color(204, 0, 0));
        lb_dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        lb_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dangxuat.setText("ĐĂNG XUẤT");
        lb_dangxuat.setOpaque(true);
        lb_dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_dangxuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_dangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_dangxuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_nhapkho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_sanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_xuatkho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_nhacungcap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(lb_khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_dangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(lb_nhapkho, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_xuatkho, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_sanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nhacungcap, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout panel_Layout = new javax.swing.GroupLayout(panel_);
        panel_.setLayout(panel_Layout);
        panel_Layout.setHorizontalGroup(
            panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_Layout.setVerticalGroup(
            panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pn_main.setPreferredSize(new java.awt.Dimension(1250, 700));

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadhome(){
        Home home = new Home();
        pn_main.removeAll();
      //  pn_main.setLayout(new BorderLayout());
        pn_main.add(home.getContentPane());
        pn_main.validate();
        pn_main.repaint();
    }
    
    
    
    private void lb_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sanphamMouseClicked
        Sanpham sv = new Sanpham();
        pn_main.removeAll();
     //   pn_main.setLayout(new BorderLayout());
        pn_main.add(sv.getContentPane());
        pn_main.validate();
        pn_main.repaint();
        
    }//GEN-LAST:event_lb_sanphamMouseClicked

    private void lb_xuatkhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_xuatkhoMouseClicked
      
    }//GEN-LAST:event_lb_xuatkhoMouseClicked

    public void setcolor(JLabel p){
       p.setForeground(Color.black);
      p.setBackground(Color.white);
    }
    
     public void resetcolor(JLabel p){
         
       p.setForeground(Color.white);
       p.setBackground(Color.decode("0x003366"));
    }
    
    
    private void lb_xuatkhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_xuatkhoMouseEntered
        // TODO add your handling code here:
        setcolor(lb_xuatkho); 
    }//GEN-LAST:event_lb_xuatkhoMouseEntered

    private void lb_xuatkhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_xuatkhoMouseExited
        // TODO add your handling code here:
        resetcolor(lb_xuatkho);
    }//GEN-LAST:event_lb_xuatkhoMouseExited

    private void lb_sanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sanphamMouseEntered
        // TODO add your handling code here:
         setcolor(lb_sanpham); 
    }//GEN-LAST:event_lb_sanphamMouseEntered

    private void lb_sanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sanphamMouseExited
        // TODO add your handling code here:
        resetcolor(lb_sanpham);
    }//GEN-LAST:event_lb_sanphamMouseExited

    private void lb_nhacungcapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhacungcapMouseEntered
        // TODO add your handling code here:
         setcolor(lb_nhacungcap); 
    }//GEN-LAST:event_lb_nhacungcapMouseEntered

    private void lb_nhacungcapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhacungcapMouseExited
        // TODO add your handling code here:
         resetcolor(lb_nhacungcap);
    }//GEN-LAST:event_lb_nhacungcapMouseExited

    private void lb_khachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khachhangMouseEntered
        // TODO add your handling code here:
        setcolor(lb_khachhang); 
    }//GEN-LAST:event_lb_khachhangMouseEntered

    private void lb_khachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khachhangMouseExited
       resetcolor(lb_khachhang);
    }//GEN-LAST:event_lb_khachhangMouseExited

    private void lb_dangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangxuatMouseEntered
        // TODO add your handling code here:
        setcolor(lb_dangxuat);
    }//GEN-LAST:event_lb_dangxuatMouseEntered

    private void lb_dangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangxuatMouseExited
        // TODO add your handling code here:
        resetcolor(lb_dangxuat);
    }//GEN-LAST:event_lb_dangxuatMouseExited

    private void lb_dangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangxuatMouseClicked
       System.exit(0);
    }//GEN-LAST:event_lb_dangxuatMouseClicked

   
   
    
    
    
    private void lb_nhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhacungcapMouseClicked
//        KhachHang kh = new KhachHang();
//        pn_main.removeAll();
//        //pn_main.setLayout(new BorderLayout());
//        pn_main.add(kh.getContentPane());
//        pn_main.validate();
//        pn_main.repaint();
//        
    }//GEN-LAST:event_lb_nhacungcapMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void lb_nhapkhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhapkhoMouseExited
        resetcolor(lb_nhapkho);
    }//GEN-LAST:event_lb_nhapkhoMouseExited

    private void lb_nhapkhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhapkhoMouseEntered
        setcolor(lb_nhapkho);
    }//GEN-LAST:event_lb_nhapkhoMouseEntered

    private void lb_nhapkhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhapkhoMouseClicked
//        Home home = new Home();
//        pn_main.removeAll();
//        // pn_main.setLayout(new BorderLayout());
//        pn_main.add(home.getContentPane());
//        pn_main.validate();
//        pn_main.repaint();
    }//GEN-LAST:event_lb_nhapkhoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_dangxuat;
    private javax.swing.JLabel lb_khachhang;
    private javax.swing.JLabel lb_nhacungcap;
    private javax.swing.JLabel lb_nhapkho;
    private javax.swing.JLabel lb_sanpham;
    private javax.swing.JLabel lb_xuatkho;
    private javax.swing.JPanel panel_;
    private javax.swing.JPanel pn_main;
    // End of variables declaration//GEN-END:variables
}
