/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Truong Hiep
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        inithome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_home = new javax.swing.JLabel();
        lb_nhanvien = new javax.swing.JLabel();
        lb_sanpham = new javax.swing.JLabel();
        lb_ncc = new javax.swing.JLabel();
        lb_khachhang = new javax.swing.JLabel();
        lb_ThongKe = new javax.swing.JLabel();
        lb_admin = new javax.swing.JLabel();
        lb_dangxuat = new javax.swing.JLabel();
        pn_main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 700));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 700));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Truong Hiep\\OneDrive\\Documents\\NetBeansProjects\\DAJ\\src\\com\\image\\logo.png")); // NOI18N

        lb_home.setBackground(new java.awt.Color(0, 51, 102));
        lb_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_home.setForeground(new java.awt.Color(255, 255, 255));
        lb_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_home.setText("Home");
        lb_home.setOpaque(true);
        lb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_homeMouseExited(evt);
            }
        });

        lb_nhanvien.setBackground(new java.awt.Color(0, 51, 102));
        lb_nhanvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        lb_nhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhanvien.setText("Nhân viên");
        lb_nhanvien.setToolTipText("");
        lb_nhanvien.setAutoscrolls(true);
        lb_nhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_nhanvien.setOpaque(true);
        lb_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_nhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_nhanvienMouseExited(evt);
            }
        });

        lb_sanpham.setBackground(new java.awt.Color(0, 51, 102));
        lb_sanpham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_sanpham.setForeground(new java.awt.Color(255, 255, 255));
        lb_sanpham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_sanpham.setText("Sản phẩm");
        lb_sanpham.setOpaque(true);
        lb_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_sanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_sanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_sanphamMouseExited(evt);
            }
        });

        lb_ncc.setBackground(new java.awt.Color(0, 51, 102));
        lb_ncc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_ncc.setForeground(new java.awt.Color(255, 255, 255));
        lb_ncc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ncc.setText("Nhà cung cấp");
        lb_ncc.setOpaque(true);
        lb_ncc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_nccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_nccMouseExited(evt);
            }
        });

        lb_khachhang.setBackground(new java.awt.Color(0, 51, 102));
        lb_khachhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        lb_khachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_khachhang.setText("Khách hàng");
        lb_khachhang.setOpaque(true);
        lb_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_khachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_khachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_khachhangMouseExited(evt);
            }
        });

        lb_ThongKe.setBackground(new java.awt.Color(0, 51, 102));
        lb_ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lb_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ThongKe.setText("Thống kê");
        lb_ThongKe.setOpaque(true);
        lb_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_ThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_ThongKeMouseExited(evt);
            }
        });

        lb_admin.setBackground(new java.awt.Color(0, 51, 102));
        lb_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_admin.setForeground(new java.awt.Color(255, 255, 255));
        lb_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_admin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Truong Hiep\\OneDrive\\Documents\\NetBeansProjects\\doanJ\\src\\main\\java\\com\\image\\admin.png")); // NOI18N
        lb_admin.setText("(Admin)");
        lb_admin.setIconTextGap(3);

        lb_dangxuat.setBackground(new java.awt.Color(0, 51, 102));
        lb_dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        lb_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dangxuat.setText("Đăng xuất");
        lb_dangxuat.setOpaque(true);
        lb_dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_dangxuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_dangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_dangxuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_sanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_ncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_khachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_dangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_sanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pn_main.setPreferredSize(new java.awt.Dimension(1250, 700));

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inithome(){
        Home home = new Home();
        pn_main.removeAll();
      //  pn_main.setLayout(new BorderLayout());
        pn_main.add(home.getContentPane());
        pn_main.validate();
        pn_main.repaint();
    }
    
    
    
    private void lb_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhanvienMouseClicked
        Nhanvien nv = new Nhanvien();
        pn_main.removeAll();
     //   pn_main.setLayout(new BorderLayout());
        pn_main.add(nv.getContentPane());
        pn_main.validate();
        pn_main.repaint();
        
    }//GEN-LAST:event_lb_nhanvienMouseClicked

    private void lb_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sanphamMouseClicked
      
    }//GEN-LAST:event_lb_sanphamMouseClicked

    public void setcolor(JLabel p){
       p.setForeground(Color.black);
      p.setBackground(Color.white);
    }
    
     public void resetcolor(JLabel p){
         
       p.setForeground(Color.white);
       p.setBackground(Color.decode("0x003366"));
    }
    
    
    private void lb_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseEntered
      setcolor(lb_home); 
    }//GEN-LAST:event_lb_homeMouseEntered

    private void lb_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseExited
        resetcolor(lb_home);
    }//GEN-LAST:event_lb_homeMouseExited

    private void lb_sanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sanphamMouseEntered
        // TODO add your handling code here:
        setcolor(lb_sanpham); 
    }//GEN-LAST:event_lb_sanphamMouseEntered

    private void lb_sanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_sanphamMouseExited
        // TODO add your handling code here:
        resetcolor(lb_sanpham);
    }//GEN-LAST:event_lb_sanphamMouseExited

    private void lb_nhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhanvienMouseEntered
        // TODO add your handling code here:
         setcolor(lb_nhanvien); 
    }//GEN-LAST:event_lb_nhanvienMouseEntered

    private void lb_nhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhanvienMouseExited
        // TODO add your handling code here:
        resetcolor(lb_nhanvien);
    }//GEN-LAST:event_lb_nhanvienMouseExited

    private void lb_nccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nccMouseEntered
        // TODO add your handling code here:
        setcolor(lb_ncc); 
    }//GEN-LAST:event_lb_nccMouseEntered

    private void lb_nccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nccMouseExited
        // TODO add your handling code here:
         resetcolor(lb_ncc);
    }//GEN-LAST:event_lb_nccMouseExited

    private void lb_khachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khachhangMouseEntered
        // TODO add your handling code here:
         setcolor(lb_khachhang); 
    }//GEN-LAST:event_lb_khachhangMouseEntered

    private void lb_khachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khachhangMouseExited
        // TODO add your handling code here:
         resetcolor(lb_khachhang);
    }//GEN-LAST:event_lb_khachhangMouseExited

    private void lb_ThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThongKeMouseEntered
        // TODO add your handling code here:
        setcolor(lb_ThongKe); 
    }//GEN-LAST:event_lb_ThongKeMouseEntered

    private void lb_ThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ThongKeMouseExited
       resetcolor(lb_ThongKe);
    }//GEN-LAST:event_lb_ThongKeMouseExited

    private void lb_dangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangxuatMouseEntered
        // TODO add your handling code here:
        setcolor(lb_dangxuat);
    }//GEN-LAST:event_lb_dangxuatMouseEntered

    private void lb_dangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangxuatMouseExited
        // TODO add your handling code here:
        resetcolor(lb_dangxuat);
    }//GEN-LAST:event_lb_dangxuatMouseExited

    private void lb_dangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangxuatMouseClicked
       System.exit(0);
    }//GEN-LAST:event_lb_dangxuatMouseClicked

   
   
    
    
    
    private void lb_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khachhangMouseClicked
        KhachHang kh = new KhachHang();
        pn_main.removeAll();
        //pn_main.setLayout(new BorderLayout());
        pn_main.add(kh.getContentPane());
        pn_main.validate();
        pn_main.repaint();
        
    }//GEN-LAST:event_lb_khachhangMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void lb_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseClicked
       Home home = new Home();
        pn_main.removeAll();
       // pn_main.setLayout(new BorderLayout());
        pn_main.add(home.getContentPane());
        pn_main.validate();
        pn_main.repaint();
    }//GEN-LAST:event_lb_homeMouseClicked

    private void lb_nccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nccMouseClicked
       Doitac dt = new Doitac(); 
        pn_main.removeAll();
       // pn_main.setLayout(new BorderLayout());
        pn_main.add(dt.getContentPane());
        pn_main.validate();
        pn_main.repaint();
    }//GEN-LAST:event_lb_nccMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_ThongKe;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_dangxuat;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_khachhang;
    private javax.swing.JLabel lb_ncc;
    private javax.swing.JLabel lb_nhanvien;
    private javax.swing.JLabel lb_sanpham;
    private javax.swing.JPanel pn_main;
    // End of variables declaration//GEN-END:variables
}
